name: Publish Package to PyPI
on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
        python setup.py install
    - name: Run tox tests
      run: tox
    - name: Build Artifact
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      if: success()
      with:
        user: __token__
        password: ${{ secrets.pypi_test_token }}
        repository: https://test.pypi.org/legacy/
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      if: success()
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}