name: Python Tox
on: 
  push:
    paths:
    - '**'

jobs:
  test:
    name: Runs Python tox tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Run tox
      run: tox -c tox-push.ini
